[build-system]
requires = ["setuptools>=69", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "warpcompress"
version = "0.1.0"
description = "Massive-file-ready, parallel, lossless compressor with mmap scatter–gather I/O and adaptive throughput mode."
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Shakeeb Salman", email = "you@example.com" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: System :: Archiving :: Compression",
  "Intended Audience :: Developers"
]

dependencies = [
  "zstandard>=0.22",
  "lz4>=4.3",
  "python-snappy>=0.7",
  "brotli>=1.1"
]

[project.optional-dependencies]
hashes = ["blake3>=0.4", "xxhash>=3.4"]

[project.scripts]
warp-compress = "warpcompress.cli:main"  # or :app if you use Typer

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}

[project.urls]
Homepage = "https://github.com/shakeeb1532/warpcompress"
Issues = "https://github.com/shakeeb1532/warpcompress/issues"
