name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write   # Needed for PyPI Trusted Publishing (OIDC)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build package (sdist & wheel)
        run: |
          python -m pip install -U pip build
          python -m build

      - name: Verify metadata (optional but helpful)
        run: |
          python -m pip install -U twine
          python -m twine check dist/*

      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
